const promptKeys = {
    basketBall: [
        `A high-energy, tight composition featuring three players from each team lined up side by side, facing each other, with a basketball trophy positioned near their eye level atop a podium in the center of the scene. Captured from a mid-shot perspective, the camera focuses on the players' expressions and the gleaming trophy, creating an intimate and intense atmosphere. On the left, the first player in an orange jersey stands tall with complete confidence, his body upright and strong, chin raised slightly to convey self-assurance. He is Black, with his eyes locked on the opposing team, and his hand grips the basketball, poised for action. Behind him, the other two players in orange, one of whom is White with short hair and a trimmed beard, and the other Black, stand straight, exuding confidence, with their chins slightly lifted and their postures reflecting readiness and determination. On the right, the opposing grey team mirrors the formation. The lead player, a bald-headed Black man in a grey jersey, stands tall in a defensive stance, his chin raised to convey confidence and resolve. His body is upright, ready to react to any move, while his intense eyes stay fixed on the orange player. The remaining two grey players, one of whom is White with short hair and a trimmed beard, and the other Asian-American, stand behind him with confident postures, creating a strong, defensive presence. The basketball trophy, positioned near eye level, gleams under dramatic lighting. A white spotlight shines down on the trophy, highlighting its polished surface and backlighting it with a glowing halo that symbolizes victory. The wisps of smoke around the players' faces are minimized, allowing more focus on the backlit scene and the radiant trophy. The background is darker and more intense, with soft hints of a cheering crowd and stadium architecture subtly illuminated in the distance. This creates a deeper sense of focus on the players and trophy, emphasizing the high-stakes atmosphere. A bold, thick orange vector line runs diagonally behind the players and trophy, adding structure and directing the viewer’s attention. Thin, short supporting vector lines enhance the dynamic energy and intensity of the moment. The backlighting casts deep shadows on the players, accentuating their muscular tension, focused expressions, and confident stances. The polished basketball court reflects the light, heightening the cinematic feel of the composition. This tighter, backlit design perfectly captures the high-stakes energy of the moment, making it ideal for mobile landscape viewing. [imagefx] (seed 475703)`,
        `A high-energy composition featuring a dramatic basketball face-off between two teams, captured in a dynamic moment. The scene is framed from a low, exaggerated angle to emphasize the intensity of the confrontation. On one side, a player in an orange jersey, wearing a focused expression, stands poised with the ball held just above the ground, ready to make a move. On the other side, a player in a dark grey jersey, crouched in a defensive stance, locks eyes with his opponent, positioning himself to counter any play. The background showcases the blurred outlines of the opposing team’s players, adding to the sense of motion and urgency. Their jerseys blur together, suggesting rapid movement and the high stakes of the face-off. A faint orange glow surrounds the players, highlighting the tension and energy of the moment. A thick, bold orange vector line runs diagonally behind the scene, directing the viewer’s focus toward the central confrontation and adding structure to the composition. Thin, semi-transparent vector lines accentuate the motion of the players, adding a dynamic layer of energy and depth. These lines overlap parts of the players and the court, enhancing the feeling of swift action and strategy unfolding in real time. The spotlight from above casts dramatic shadows on the players, highlighting the tension in their muscles and faces, while the court itself reflects the gleam of polished wood. The warm lighting gives the scene a cinematic, intense atmosphere that conveys the heat of the moment. This design is compact, immersive, and perfect for mobile landscape viewing, encapsulating the excitement and energy of a high-stakes basketball face-off. [imagefx] (seed 664979)`,
        `A captivating composition featuring a gleaming basketball trophy positioned on top of a sleek, elevated podium. The dramatic low-angle camera captures the trophy’s grandeur, with the shiny surface reflecting the warm, focused light. Atop the trophy, the shiny golden basketball glows, symbolizing victory in its pristine form. Wrapped loosely and elegantly around the base of the trophy is a removed basketball net, its white mesh flowing gently and wrapping around the bottom part of the podium, adding a dynamic sense of motion and triumph. The net softens the polished metal of the trophy, creating a contrast that elevates the design’s elegance. In the blurred background, a faint image of a basketball team celebrating is visible, their raised arms and joyful expressions subtly reinforcing the atmosphere of victory and achievement without distracting from the central focus. The warm spotlight casts dramatic highlights and soft shadows on the trophy, podium, and net, creating depth and emphasizing the intricate details. The dynamic angle, combined with the refined layout, gives the design a powerful, dramatic impact. Perfect for mobile landscape viewing, this composition captures the glory of victory, the elegance of the moment, and the celebratory energy surrounding the achievement. [imagefx] (seed 377094)`,
        `A compelling composition set in a professional athlete’s locker room, with a dramatic spotlight casting focused light on a smartphone leaning against a textured basketball. The phone’s screen glows brightly, showcasing a winning basketball bet with bold green highlights and vibrant graphics, drawing immediate attention. The basketball rests on a dark gray sports towel, its worn, orange surface contrasting against the soft folds of the towel’s fabric. To the right of the phone, a white and gray basketball shoe lies at an angle, its sleek, clean design adding subtle sophistication. To the left, a sports timer with a digital display prominently shows 1:88, its black and orange casing blending seamlessly with the scene. A dark gray sports bottle with vivid orange accents stands nearby, its metallic sheen reflecting the spotlight subtly. The background reveals a blurred professional locker room, with faint outlines of jerseys, open lockers, and athletic gear, creating a sense of realism. A thick, diagonal orange vector line runs behind the basketball and phone, adding structure and tying the elements together with a modern, bold aesthetic. Thin, short supporting vector lines overlap parts of the items, enhancing the dynamic energy of the scene without distracting from the focal point. The warm spotlight and subtle shadows create a dramatic, immersive atmosphere, perfect for mobile landscape viewing, encapsulating the thrill of victory and the preparation behind every play. [imagefx] (seed 74474)`,
        `Two male basketball players in their late 20s are captured from a more side-on angle, with a focus on an intense, high-stakes match-up and dynamic movement. The central player, a Black male in an orange jersey with dark grey accents, is caught mid-action, positioning himself for an explosive move. His body is hunched slightly forward in an aggressive stance, eyes locked on the opponent, while his left hand holds the ball close to his chest. His right arm is bent, preparing to push off and make a sudden pass or drive toward the basket. His athletic form and fierce expression convey determination and power, making him the clear focal point of the scene. To the left, a Caucasian male player, dressed in a white jersey with orange accents, is sprinting toward the Black player with intense focus. His body leans forward as he closes the distance, positioning himself to block or steal the ball. His arms are aggressively outstretched, with his right hand reaching toward the ball, while his expression is a mix of determination and urgency. His posture creates an undeniable tension as he and the Black player face off, emphasizing their battle for control of the game. The background features the Black player’s teammates slightly blurred and out of focus, heightening the sense of depth and spotlighting the tense one-on-one match-up. The basketball court and stadium lights reflect off the players’ backs, adding drama to the scene and drawing attention to their physicality. A thick, sharp orange vector line runs diagonally behind the players, providing structure and directing the viewer’s attention toward the action. Thin, short supporting vector lines overlap parts of the players, subtly accentuating their rapid movement and energy. The golden hour lighting casts dramatic shadows, highlighting the players’ tense muscles and motion, and enhancing the scene’s intensity. The layout of the players, spaced at varying depths, creates a cohesive, high-energy moment that feels urgent and dynamic. The varied angles, alongside the sharp vector lines, contribute to a modern, impactful design that captures the electric energy of the play. [imagefx] (seed 994075)`,
    ],
    csgo: [
        `A close-up shot of a soldier in tactical gear, angled slightly towards the camera in an exaggerated angle, as they advance cautiously down a narrow, dimly lit corridor in a Counter-Strike map. Golden hour light filters through cracks in the walls, casting angular shadows that highlight the soldier’s armor and weapon. Sparks fly as stray bullets narrowly miss, ricocheting off nearby surfaces and briefly illuminating the scene in flashes of warm orange and gray. In the background, a fellow Navy SEAL, slightly blurred to maintain focus on the foreground, is mid-action, diving into cover with their weapon raised. Swirling dust particles and a faint plume of smoke trail a recently dodged explosion, creating a textured and dynamic atmosphere. The soldier in focus crouches with intense precision, their weapon steady, while motion blur on their gear emphasizes their careful movement. The blurred background and the second soldier’s dynamic pose add depth. (Microsoft Designer)`,
        `Two esports teams face off in a dramatic, photorealistic portrait, each with two players, each face is unique, in their early 20s, sporting focused expressions. The right team wears dark orange jerseys with gleaming details that catch the light, while the left team sports dark gray jerseys with similar luminous accents, both seamlessly integrated with logos. Each player also wears a gaming headset, tactical gloves, and tactical vest. The players stand in a tense, head-to-head stance, arms crossed, exuding confidence and rivalry. Between them, a Navy SEAL and a SWAT operative, clad in full combat gear, charge toward the camera, adding dynamic energy to the scene. The background features a CS:GO map like Dust 2 or Mirage, with tactical grids subtly wrapping around the players. Holographic explosions and swirling smoke interact dynamically, while weapon icons hover near the operatives. HUD elements like health stats and scores glow subtly, blending seamlessly into the environment to amplify the intensity and immersion of the showdown. [ImageFX] (seed 715628)`,
        `A dramatic, photorealistic scene centers on a Navy SEAL and a SWAT operative in full combat gear, charging toward the camera with intense focus. Their detailed gear—helmets, vests, and weapons—shows slight battle damage, adding realism. The SWAT officer leans against the SEAL’s back for cover, aiming his scratched and dented weapon with determination, while the SEAL crouches low, aiming his slightly scorched rifle with precision. The glow of the golden hour bathes them both. Their powerful stances convey urgency and tension. Behind them, slightly blurred to emphasize the soldiers, two esports teams stand in a tense face-off. Each team, in their mid-20s, wears dark orange or gray jerseys with gleaming accents, paired with headsets and gloves. The backdrop features a CS:GO map like Dust 2, with tactical grids framing the scene. Holographic explosions, swirling smoke, and hovering weapon icons interact dynamically, while faint HUD elements like health stats and scores blend seamlessly, heightening the immersive intensity. [ImageFX] (seed 523593)`,
        `A giant silver trophy partially covered by smoke, sparks, and ember stands proudly just behind the soldiers, reflecting its surroundings. The golden hour glow bathes the operatives and the trophy, enhancing the tension and drama. Slightly blurred in the background, two esports teams stand in a tense face-off. Each team, in their mid-20s, wears either dark orange or gray jerseys with luminous accents, paired with headsets, tactical gloves, and tactical vests. The backdrop features a CS:GO map, with tactical grids framing the scene. Holographic explosions, swirling smoke, and hovering weapon icons interact dynamically, while faint HUD elements like health stats and scores blend seamlessly, elevating the immersive, high-stakes atmosphere. [ImageFX] (seed 44169)`,
        `A dramatic, photorealistic scene depicts a SWAT operative and a Navy SEAL in full combat gear, charging forward with exaggerated perspective to amplify their dynamic presence. The SWAT officer, now the main focus, is positioned incredibly close to the camera in the foreground, crouching for cover, aiming a scratched, dented weapon with intense focus. The SEAL, further back, targets with his scorched rifle. The SWAT officer's battle-worn helmet, tactical vest, and weapon add realism, placing him at the center of the action. In front of him, a gleaming, wide, stout silver trophy stands just behind the SWAT officer, backlit and glowing with a vibrant, intense light. The trophy is partially obscured by light smoke and floating spark particles, with thin orange lights leading towards it. In the foreground, two civilians wearing black ski masks are sprawled on the ground, dressed in sleeveless bulletproof vests that reveal tattooed arms, surrounded by scattered weapons and shell casings. The scene is bathed in warm golden hour light, highlighting the reflective surface of the glowing trophy and casting dramatic shadows over the operatives. In the distance, two esports teams are displayed within a semi-transparent HUD, each in their mid-20s and communicating through gaming headsets. The team on the left wears dark orange jerseys, while the team on the right wears light gray. [ImageFX] (seed 902128)`,
    ],
    lol: [
        `A dynamic banner featuring four 3D-stylized champions: Akali, Yasuo, Thresh, and Jhin, battling on giant LED screens in a packed esports arena. Each champion is mid-motion—Akali leaps from the shadows, Yasuo slashes through the air, Thresh swings his spectral chains, and Jhin fires a precise shot. The screens emit vibrant colors of blue, green, and gold, reflecting the energy of the cheering crowd. The center stage shows players in their gaming setups with glowing keyboards. [Microsoft Designer]`,
        `A high-energy esports banner featuring 3D-stylized League of Legends champions like Ahri casting a glowing blue orb, Yasuo unleashing a swirling whirlwind, and Jinx firing her oversized rocket launcher. Each champion is depicted with exaggerated, dynamic poses and intricate details. The backdrop shows a glowing stadium filled with an energetic crowd, with vibrant neon colors of blue, purple, and orange against a dark, dramatic background. [Microsoft Designer]`,
        `A dynamic banner featuring four champions — Akali , Yasuo , Thresh, and Jhin —battling on LED screens in a packed esports arena . Each champion is mid-motion: Akali dashes with smoky trails, Yasuo slashes through wind currents, Thresh swings his spectral chains, and Jhin fires a precision shot. In the center of the arena, an ancient trophy sits on a glowing stone pedestal, surrounded by swirling magical energy. The trophy has a timeless design, with dragon motifs curling along its base, glowing runes , and an orb of radiant light at its apex. The backdrop mixes ancient stone textures with futuristic lighting . [imageFX seed:741136]`,
        `A high-energy esports banner featuring realistic League of Legends champions like Ahri casting a glowing blue orb , Yasuo unleashing a swirling whirlwind , and Jinx firing her oversized rocket launcher. Each champion is depicted with exaggerated , dynamic poses and intricate details . The backdrop shows a glowing stadium filled with an energetic crowd , with vibrant neon colors of blue , purple , and orange against a dark , dramatic background . [imageFX seed:741136]`,
    ],
    parlay: [
        `A photo-realistic modern smartphone leans against a gold and black soccer ball, its screen glowing as a vibrant gray and gold parlay betting slip emerges from the screen. Below, gold coins scatter outward, interspersed with small, elegant gift boxes wrapped in metallic gold and black ribbons, adding a sense of luxury and excitement. Subtle gold streaks of light extend outward from the betting slip, serving as leading lines that draw the eye back to the focal point. Faint streaks of swirling grass enhance the motion, while the background fades into a blurred stadium with soft glowing lights, blending dynamic energy with subtle elegance. [Shakker]`,
        `A photorealistic dark gray and orange parlay betting slip hovers mid-air , seamlessly integrated with dynamic sports imagery—a prominent soccer ball curves around one corner of the slip, a basketball spins gently beside it, and a tennis ball appears to bounce off its edge—creating a sense of interaction and movement. Subtle glowing lines in orange and silver radiate outward, connecting the slip to the sports elements in a cohesive flow . The minimalist background transitions to a softly lit stadium with faint, blurred stands and understated field lights, enhancing focus without distraction. A smooth , reflective dark surface grounds the design, while the cohesive color scheme of #FF9200, #C3C3C3, #262626, and #FFFFFF adds elegance and harmony. [ImageFX](seed 345873)`,
        `The design features a photo-realistic , shiny , glowing betting slip in a rich , metallic #a7a6a7 color with dark gray and orange accents, resting atop a gleaming metallic podium . The slip emits a soft golden glow as its bottom part wraps elegantly around the podium in smooth arcs , seamlessly interacting with the podium and coins . Blank gold coins scatter across the base, flowing over and beneath the slip, while flying coins ricochet off its edges, adding dynamic motion and depth. Behind it, a single blurred large-screen TV on a table in a stadium displays a vibrant sports match. Thin golden streaks of light on the floor guide the viewer’s eye, completing a lifelike, immersive design. [ImageFX](seed 429923)`,
        `A photo of a photorealistic scene bursting with energy and excitement. The focal point is a glowing golden parlay paper betting slip in metallic tones with orange and dark gray accents. Behind it, a sleek smartphone displays a photorealistic vivid soccer field that dynamically emerges from its screen, creating depth and interaction. A large screen behind the phone showcases a live soccer match , amplify ing the intensity of the moment. A polished golden soccer ball rests nearby, adding luxury. All the elements are on top of trimmed grass on the soccer field. Soccer players in orange and white jerseys charge towards the phone in the background , reinforcing action and engagement. The softly blurred , well-lit stadium background ensures all elements converge seamlessly around the betting slip, amplify ing its significance .  [ImageFX](seed 494543)`,
        `A high-energy photorealistic scene focused up-close on a glowing parlay betting slip standing tall and upright, slightly angled but mainly facing the camera. The slip, crafted in a rich metallic gold color with dark gray and orange accents, is shiny , detailed , and distinctly paper-like , with a slight, natural bend adding text ure and realism. The text on the betting slip is large, bold , and easy to read , ensuring the details of the bets and odds are clearly visible, enhancing the focal impact. Peeking out from behind the betting slip is a polished soccer ball and a gold trophy, subtly adding depth and reinforcing the theme. Towering in the foreground, the slip commands attention and symbolizes the stakes . Surrounding it, a few small flying blades of grass float mid-air on both foreground and background adding motion and energy to the scene. Slightly blurred in the background are two soccer teams in the midst of a face-off —two players in crisp white jerseys on left side and two players in a bright orange jerseys on the right, frozen in a tense, mid-action stance. The trimmed green grass of the soccer field forms the base, with soft bokeh stadium lights glowing in the distance. The atmosphere is electric , with the tall, prominent betting slip, the soccer ball , trophy, and the dynamic energy of the players seamlessly integrating to heighten the thrill of sports betting. ([ImageFX](seed 494543)`,
    ],
    dota2: [
        `A stunning, photorealistic image of the Dota 2 trophy as the central focus, surrounded by a flowing golden ribbon that winds around it with elegant motion. The trophy should be detailed and gleaming, reflecting light with intricate designs that showcase its prestigious nature. The golden ribbon should swirl gracefully around the trophy, shimmering and creating a sense of triumph and celebration. The background should be a soft, blurred arena scene with dimmed lights, enhancing the focus on the trophy. The overall atmosphere should evoke a sense of grandeur, success, and excitement, with glowing accents to emphasize the magical and competitive spirit of the tournament. [Microsoft Designer]`,
        `Create an intense image of a Dota 2 player wearing a gaming headset, sitting at their desk with their head slightly down but facing forward, eyes focused intently on the screen. The player’s hands should glow with powerful, radiant energy, as if channeling magic, with light trails, sparks, and mystical symbols emanating from their palms. The energy should feel dynamic and forceful, symbolizing the connection between the player and the game. The background should feature a dark, atmospheric gaming room, with the glow of the computer screen illuminating the player's intense expression. Use a color palette of deep blues, purples, and fiery oranges to reflect the power and intensity of the moment. The overall design should evoke immersion, concentration, and the competitive nature of Dota 2.  [Microsoft Designer]`,
        `A powerful Dota 2 banner featuring iconic heroes in a dynamic, action-packed scene. The heroes should be positioned in striking battle stances, each showcasing their unique abilities. For example, a spell-casting hero like Invoker can be channeling powerful magic, while a strength hero like Axe might be in mid-swing with his axe, and an agility hero like Mirana could be poised with her bow. Surround them with vibrant energy effects, glowing trails, and elemental power, representing their abilities in action. The background should be a dramatic battlefield, with mystical terrain, glowing runes, and magical energy pulses filling the space. The lighting should be intense, with a spotlight on each hero, and a dark, stormy sky above to amplify the tension of the moment. The color palette should feature bold, contrasting tones—electric blues, fiery reds, and vivid greens—to reflect the magical and competitive nature of Dota 2. The overall design should be high-energy, emphasizing the unique powers of the heroes while creating a cohesive and epic visual story.  [Microsoft Designer]`,
        `A high-energy image of two groups of Dota 2 players standing side by side, shouting with intensity and passion, with a trophy at the center. The players wear esports jerseys, surrounded by glowing effects and team colors. The background features a dimly lit arena with dramatic lighting, a roaring crowd, and subtle Dota 2 elements like hero icons and glowing runes. Use vibrant colors and dynamic lighting to capture the excitement, camaraderie, and competitive spirit of the tournament.  [Microsoft Designer]`,
        `A sleek Dota 2 banner showcasing two iconic heroes locked in an intense battle, surrounded by glowing gold coins and highlighted betting odds. Set against a futuristic arena backdrop with vibrant lights and a cheering crowd, include bold 3D text reading 'Bet on the Action!' with glowing accents to emphasize key offers. Use a dynamic color palette of fiery reds, electric blues, and gold to convey the thrill of the game and the excitement of betting.  [Microsoft Designer]`,
    ],
    football: [
        `A vibrant, photorealistic sportsbook web banner with a dynamic and eye-catching composition. Feature a gift box, trophy, and soccer ball as the central focal points, glowing with radiant highlights to immediately capture attention. Surround these key elements with shimmering gold coins and subtle celebratory accents to evoke excitement and the allure of rewards. The background should transition into a dramatic, softly blurred stadium scene, bathed in the warm, golden hour light to add depth and a sense of grandeur. Use a clean, well-organized layout that ensures clarity, visual impact, and seamless adaptability for both desktop and mobile platforms.  [ImageFX] (seed 884344)`,
        `A celebratory and vibrant banner to congratulate Indonesia team for winning the Asia football cup. Place the team's flag and bold text that reads 'AFC Champions' prominently over a glowing golden trophy at the center. Surround this with dynamic action shots or silhouettes of key players celebrating, such as lifting the trophy or cheering . Use a dramatic stadium background with glowing floodlights , cascading confetti , and a festive fireworks display to enhance the excitement. Incorporate gold laurel wreaths , shimmering stars , and the championship year to emphasize prestige. Use a color palette of gold, white , and the team's colors for a bold and elegant design. Ensure the layout is clean and balanced , with optional space for sponsor or league logos, and optimized for readability across digital and mobile platforms.  [MICROSOFT DESIGNER]`,
        `A photorealistic image of the AFF Cup, capturing the essence of the competition. Feature three dynamic football players in high-intensity action at the center, showcasing their athleticism and passion. Surround them with celebratory elements like cascading confetti, gleaming gold medals, and flowing ribbons, symbolizing the excitement and triumph of the games. The background should depict a dramatic football stadium filled with roaring fans and brightly shining floodlights, enhancing the atmosphere of intensity and celebration. Use a bold color palette of deep blues, rich golds, and the participating nations' colors to evoke a cohesive, global feel. The design should be clean, visually impactful, and optimized for both desktop and mobile viewing, seamlessly integrating text and imagery. [MICROSOFT DESIGNER]`,
        `Create an image of a soccer next to a phone displaying a orange 188bet website, placed on a pile of gold coins. Add glowing effects around the phone and coins, with a blurred stadium background featuring bright lights and a cheering crowd.[MICROSOFT DESIGNER]`,
        `A hyper realistic image for a sportsbook website showcasing its stake rewards program. The image feature a large, attention-grabbing headline that says 'Boost Your Bets with Stake Rewards!' in bold, energetic typography. Include a visual of a sports betting account screen showing a user's rewards balance increasing as they place bets. Surrounding the screen, show a mix of sports-related icons (football, basketball, tennis ball, etc.) and glowing gold coins to symbolize winnings and rewards. Add a visual effect of coins or rewards stacking up, suggesting growth and excitement. In the background, include a blurred sports stadium filled with action, such as players on the field, and bright lights to enhance the atmosphere of excitement. The design should be modern and vibrant , with colors like gold, green , and blue to signify prosperity and trust. [ImageFX] (seed 981058)`,
    ],
    ftd: [
        `A photorealistic image featuring bold 3D text ' 100% ' in gold slightly facing left showing depth, prominently displayed at the center sitting on top of stacked casino chips . with a luxurious casino theme. Use a black and gold color scheme, incorporating golden elements like dice , poker chips , roulette wheels , playing cards (e.g., ace , king , queen , jack ), soccer ball and basketball . Surround the scene with subtle glowing effects , sparkles , and light beams for a glamorous and dynamic atmosphere. Place the design on a dark background with a spotlight effect to emphasize the central elements.  [ImageFX] (seed 110033)`,
        `A photorealistic image featuring bold 3D text ' 100% ' in  yellow gold, placed on the grass with spotlight effect to emphasize the central element. text is surrounded with sports and casino elements such as golden dice, black gold poker chips, roulette wheels , soccer ball , basketball and playing cards (e.g., ace , king, queen, jack ) each has depth and movement, while the background fades into a blurred stadium with soft glowing lights and scene has subtle glowing effects, sparkles , and light beams . sideward camera view  [Shakker]`,
        `A hyper realistic image showcasing bold 3D text reading ' 100% ' in gleaming, radiant gold. The text stands out prominently, symbolizing a special offer for first-time deposit members. The ' 100% ' bursts dynamically from the screen of a sleek smartphone displaying the sports betting interface, surrounded by vibrant light effects and glowing trails . Encircling the phone are dynamic, high-energy elements such as golden dice, shimmering coins , a glossy soccer ball , a polished slot machine, and detailed playing cards, each floating in mid-air to emphasize the excitement of the offer. The backdrop features a softly blurred, illuminated stadium with faint stands and glowing field lights , creating an immersive atmosphere that highlights the exclusive promotion while maintaining a clean and focused design.  [ImageFX] (seed 875209)`,
        `A high-tech vault door swings open, revealing bold 3D '100%' in radiant gold, symbolizing a first-time deposit bonus. Golden light beams, tumbling coins, holographic dice, and a spinning soccer ball burst forth, surrounded by glowing playing cards. Set in a futuristic arena with sleek metallic textures, neon accents, and holographic betting displays, the scene exudes energy and exclusivity, inviting users to unlock their premium offer.  [Microsoft Designer]`,
        `A majestic archway, designed like a championship trophy, takes center stage, with bold 3D '100%' in gleaming, reflective gold proudly hovering at its peak. Radiant golden light beams spill outward, illuminating dynamic elements: spinning soccer balls, cascading coins, tumbling dice, and fluttering playing cards flowing energetically through the arch, capturing the excitement of betting.The background showcases a grand stadium bathed in spotlight beams, with the faint roar of cheering crowds visible in the blurred distance, adding energy and scale. A sleek digital banner spans the arch, boldly proclaiming “100% Bonus for First-Time Deposits!” while a glowing call-to-action button below, reading “Claim Now!”, pulses subtly to draw attention. This design exudes triumph and excitement, inviting users to step into the ultimate betting experience. [Shakker]`,
    ],
    freebet: [
        `A 3D photorealistic scene of a football stadium at dusk. A golden "Freebet" ticket lies at the center of the vibrant green field, slightly folded and glowing, surrounded by shimmering golden coins and a spinning classic football. Bright stadium lights illuminate the field, casting soft shadows and highlighting the ticket as the focal point. [Microsoft Designer]`,
        `A 3D photorealistic scene set in a football stadium at dusk. A glowing golden 'Freebet' ticket dominates the vibrant green field, angled dynamically as if about to launch. Beside it, a spinning football and shimmering golden coins add motion and balance. Bright stadium lights and dramatic shadows enhance the depth, highlighting the glowing ticket and rich textures of the grass. [Microsoft Designer]`,
        `A dramatic sports betting banner in a football stadium at golden hour. A massive green & gold 'Freebet Ticket' dominates the vibrant green field, surrounded by a football, basketball, gold trophy, and scattered golden coins. Warm sunset light casts realistic shadows, enhancing the colors and emphasizing the ticket's grandeur in a clean, dynamic design. [Microsoft Designer]`,
        `A dramatic sports betting banner set in a football stadium during golden hour. A glowing golden 'Freebet' dominates the vibrant green field, surrounded by a soccer ball, orange basketball, gold trophy, and scattered golden coins in dynamic motion. Warm sunset light enhances the richness of the colors, casting realistic shadows and emphasizing the grandeur of the scene. [imageFX seed:741136]`,
        `A futuristic arena with a curved , glowing structure in dark metallic tones and accents of golden yellow and vibrant orange (#FF9200). A semi-transparent 3D sports ticket hovers mid-air, with glowing edges in golden yellow and “ FREEBET ” displayed in bold, luminous #FFFFFF letters. Surrounding the ticket are floating , stylized sports elements, such as a soccer ball and coins , rendered with metallic finishes in golden hues and subtle orange highlights, creating a cohesive and radiant composition. [imageFX seed:741136]`,
        `A dark, modern background with subtle textures, like brushed metal or carbon fiber. A glowing neon green or orange "FREEBET" stands out as the focal point, illuminated in the dark. Surrounding it are realistic, semi-transparent silhouettes of a soccer ball, basketball, tennis ball, badminton shuttlecock, and a trophy, adding dynamic sports elements to the composition. [imageFX seed:741136]`,
    ],
    rebate: [
        `Create a hyper-realistic 3D scene with detailed textures. The focal point is a large, glowing "50% Rebate" sign embedded in a luxurious, polished casino-style signage with sharp, realistic lighting and reflective surfaces. The "50% Rebate" text is bold, glowing neon within a high-end, sleek metallic frame. The neon emits a realistic glow, casting soft light reflections on nearby elements, including glass surfaces and polished floors. In the middle-ground, a hyper-detailed spinning roulette wheel with glowing neon accents is surrounded by flying neon coins with metallic reflections, moving in slow motion around the sign to create a dynamic blur. The background includes realistic casino elements such as shimmering gold poker chips, slot machines with lifelike textures, and sports icons like a soccer ball and basketball, all slightly blurred to enhance depth. A modern mobile phone displays a betting app in the background, with crisp, high-resolution screen details. Lighting features harsh contrast between the brightly illuminated "50% Rebate" sign and the more softly lit background. Subtle reflections and shadows enhance depth and realism, with ambient light bouncing naturally off nearby surfaces. The scene should feel immersive and vibrant, bringing a neon casino world to life with rich, photorealistic detail. [ImageFX] (seed 400950)`,
        `Design a vibrant 3D scene in Pixar style with neon lighting. The main focus is a large, glowing "50% Rebate" text inside a dynamic, retro casino-style signage with animated neon lights and subtle reflections on nearby surfaces. In the middle-ground, a spinning roulette wheel with neon accents is surrounded by flying neon coins orbiting around the sign, creating a sense of motion. The background features faded, smaller casino elements like neon-lit poker chips, slot machines, and stylized sports icons such as a soccer ball and basketball. A modern mobile phone displaying a betting app adds to the theme. Bright, saturated neon lights highlight the foreground signage, while the middle-ground and background are softly illuminated to create depth. The atmosphere blends a playful Pixar aesthetic with a glowing, interactive casino environment. [ImageFX]`,
        `Hyper-realistic 3D casino scene with centered "50% Rebate" signageCreate a hyper-realistic 3D scene from a worm’s-eye view, with the "50% Rebate" text centered in the foreground inside a polished, luxury casino-style sign. The sign should have metallic details and warm, ambient lighting, with subtle reflections on nearby surfaces. In the middle-ground, include a mobile phone releasing glowing coins into the air, creating a sense of motion. In the background, a softly blurred roulette wheel and a few faint casino elements, such as poker chips. Use realistic lighting and shadows to enhance depth and highlight the luxurious atmosphere.`,
        `Hyper-realistic 3D casino scene with centered "50% Rebate" signageCreate a hyper-realistic 3D scene from a worm’s-eye view, with the "50% Rebate" text centered in the foreground inside a polished, luxury casino-style sign. The sign should have metallic details and warm, ambient lighting, with subtle reflections on nearby surfaces. In the middle-ground, include a mobile phone releasing glowing coins into the air, creating a sense of motion. In the background, a softly blurred roulette wheel and a few faint casino elements, such as poker chips. Use realistic lighting and shadows to enhance depth and highlight the luxurious atmosphere.`,
        `Design a vibrant 3D scene in Pixar style with neon lighting. The main focus is a large, glowing "50% Rebate" text inside a dynamic, retro casino-style signage with animated neon lights and subtle reflections on nearby surfaces. In the middle-ground, a spinning roulette wheel with neon accents is surrounded by flying neon coins orbiting around the sign, creating a sense of motion. The background features faded, smaller casino elements like neon-lit poker chips, slot machines, and stylized sports icons such as a soccer ball and basketball. A modern mobile phone displaying a betting app adds to the theme. Bright, saturated neon lights highlight the foreground signage, while the middle-ground and background are softly illuminated to create depth. The atmosphere blends a playful Pixar aesthetic with a glowing, interactive casino environment. [ImageFX]`,
    ],
    referral: [
        `A hyper-realistic banner featuring a sleek smartphone prominently displayed at the top, its screen glowing and displaying a detailed sports betting page with live odds, match details, and a vibrant "Bet Now" button. Emerging from the smartphone screen is a bold, 3D megaphone with realistic details, projecting outward into the scene. Floating out of the screen alongside the megaphone is a glowing "Add a Friend" icon, depicted as a stylized silhouette of two people with a plus sign. In the foreground, a joyful person in dynamic motion is holding a shining stack of gold coins and gift cards, the coins gleaming as they catch the light. The background is an energetic burst of colors—red, orange, and yellow—blending into a sleek, futuristic design with subtle light streaks and sparkles to add depth. [Microsoft Designer]`,
        `A hyper-realistic banner featuring a sleek smartphone prominently displayed at the top, its screen glowing and displaying a detailed sports betting page with predicted odds , betting trends , and a vibrant " Sign Up " button. Emerging from the smartphone screen is a bold, 3D megaphone with realistic details, projecting outward into the scene. Floating out of the screen alongside the megaphone is a glowing " Refer a friend " icon, depicted as a stylized silhouette of two people with a plus sign. In the foreground, a joyful person in dynamic motion is holding a shining stack of gold coins and discounts, the coins gleaming as they catch the light. The background is an energetic burst of colors— yellow , orange , and white —blending into a sleek, futuristic design with subtle light streaks and sparkles to add depth. [imageFX seed:820377]`,
        `Two gift boxes —one larger with an orange ribbon, the other smaller—sitting side-by-side on a stylish table. A smartphone rests next to them, its screen brightly displaying a referral bonus banner  on a dark grey and  light grey website with a few orange accents, the text "REFERRAL BONUS" is visible. The scene is illuminated by warm lighting, and the background suggests a celebratory atmosphere with faint champagne glasses visible. [imageFX seed:120945]`,
    ],
    matchBanner: [
        `A hyper-realistic, worm’s-eye view perspective showcasing an epic match poster for the Basketball League Championship 2025 between China and Japan. At the center is a large, gleaming gold trophy with "Basketball League Championship 2025" elegantly engraved, surrounded by bold, dramatic "VS" text that overlaps and emphasizes the intense upcoming clash. The national flags of China and Japan, trimmed in gold, are displayed prominently on elevated platforms, viewed from below to enhance grandeur and anticipation. The composition is dynamic and powerful, with vibrant color contrast and a cinematic, larger-than-life tone. The background features a grand basketball stadium with dramatic lighting and shadow play that highlights the towering platforms and flags as symbols of national pride. Subtle basketball elements—like a court floor texture or hoops—are integrated into the background. To amplify the epic feel, the scene includes perspective dynamics: speedlines, depth effects, and exaggerated angles, creating energy and immersion. The overall tone is competitive, powerful, and visually striking, with sharp details and bold colors that focus attention on the trophy, flags, and "VS" text. [imageFX]`,
        `A hyper-realistic, worm’s-eye view perspective showcasing an epic match poster for the Basketball League Championship 2025 between China and Japan. At the center is a large, gleaming gold trophy with "Basketball League Championship 2025" elegantly engraved, surrounded by bold, dramatic "VS" text that overlaps and emphasizes the intense upcoming clash. The national flags of China and Japan, trimmed in gold, are displayed prominently on elevated platforms, viewed from below to enhance grandeur and anticipation. The composition is dynamic and powerful, with vibrant color contrast and a cinematic, larger-than-life tone. The background features a grand basketball stadium with dramatic lighting and shadow play that highlights the towering platforms and flags as symbols of national pride. Subtle basketball elements—like a court floor texture or hoops—are integrated into the background. To amplify the epic feel, the scene includes perspective dynamics: speedlines, depth effects, and exaggerated angles, creating energy and immersion. The overall tone is competitive, powerful, and visually striking, with sharp details and bold colors that focus attention on the trophy, flags, and "VS" text. [imageFX]`,
        `A hyper-realistic , worms-eye view perspective showcasing an epic match poster for a soccer game between China and Japan. At the center of the image is a large, gleaming gold trophy with text "Soccer League Championship 2025" and with bold "VS" text in a dramatic, overlapping, emphasizing the intense upcoming clash. The flags of China and Japan are displayed prominently on elevated platforms with gold edges viewed from below to enhance the sense of grandeur and anticipation. The overall composition is dynamic and powerful , with a focus on strong contrast and vibrant colors , giving the scene a cinematic , larger-than-life feel. The background is subtly blurred to keep attention on the central elements, with the platform and flags standing tall as symbols of national pride. The background features a grand soccer stadium with an epic lighting grade , casting dramatic shadows and enhancing the atmosphere. The entire composition should feel powerful , competitive , and visually striking , with a mix of sharp detail and bold colors and some soccer elements. Add some perspective dynamic s to look more epic.  [imageFX]`,
    ],
    multipleSports: [
        `A vibrant, photorealistic scene of ecstatic celebrations from a soccer player, a basketball player, and an F1 driver, all interacting in a shared moment of triumph as they celebrate with a trophy. The shot is closer, with the athletes standing back-to-back, leaning on one another while still facing the camera. Each of them places one hand on the trophy in the center, holding it together in a united gesture of victory. The athletes, dressed in a unified combination of orange and dark gray, form a dynamic trio. A sharp diagonal orange vector cuts across the players, adding a modern and dynamic feel to the composition, creating a sense of movement and energy. A few very thin, semi-transparent orange vectors run parallel to the existing diagonal, subtly enhancing the visual impact and modernity of the scene without overwhelming the composition. The soccer player, mid-air in celebration, has just scored, while the basketball player beside them extends their arm to high-five, both leaning toward each other in a moment of pure joy. The F1 driver stands behind them, gesturing to the other two athletes with their helmet raised in a triumphant gesture, a deep look of exhilaration on their face. The tighter shot brings the athletes closer together, highlighting their unity and shared victory with the trophy at the center of their interaction. The low camera angle emphasizes their celebration, creating an almost larger-than-life effect. The golden hour light bathes the scene, casting a soft yet vibrant glow, with the background softly blurred to keep the focus on the athletes. This composition enhances their interaction, drawing the viewer into their shared moment of glory, perfect for a mobile landscape layout without the distraction of confetti. (ImageFX) [seed 983547]`,
        `A compact, high-energy design where soccer, basketball, and tennis are tightly woven together, leaving minimal negative space. The composition is intense and close-up. In the center, the basketball player, wearing an orange jersey, is mid-dunk, his body filling the frame with the ball about to slam through the net. To the right, the soccer player, dressed in a dark grey jersey, locks his foot in motion, almost touching the basketball player’s arm as the ball heads toward the goal. The tennis player, also in an orange jersey, swings their racket sharply from the left, blending its motion with the soccer action, the tennis ball frozen just before contact. A thick, diagonal orange vector runs behind the elements, tying them together and enhancing the modern, dynamic feel. All elements are packed tightly, with each sport's motion blending fluidly to create a sense of speed and momentum. The design focuses on the athletes in motion, with no wasted space, resulting in a cohesive, fast-paced banner perfect for a mobile landscape layout. [ImageFX](seed 196800)`,
        `Create a high-energy, dynamic composition featuring three athletes: a soccer player, a basketball player, and a tennis player, arranged closely together with minimal negative space. The composition should use a dramatic worm’s-eye view to make the athletes appear larger and more powerful. In the foreground, the soccer player, wearing an orange jersey with white accents, is in motion, running towards a soccer ball positioned slightly above eye level. He’s about to leap and strike the ball with his head, with his body leaning forward, arms outstretched, and eyes locked on the ball. He is shouting instructions to teammates, creating a sense of intensity. The entire scene is illuminated with golden hour lighting, casting warm glows and long shadows that emphasize the athletes' movements and physicality. To the left, the basketball player, dressed in a dark grey jersey with orange accents, dribbles the ball low to the ground, facing the camera. The golden lighting reflects off the ball, adding depth to the composition. To the right, the female tennis player in a white jersey is captured mid-swing, executing a backhand shot, with her racket slicing through the air. The warm lighting highlights her powerful motion. The background should subtly feature a stadium, enhancing the atmosphere, while golden hour lighting adds warmth to the mood. A bold, diagonal orange vector runs behind the athletes, tying the composition together, with thin, semi-transparent vector lines parallel to it, adding additional layers and depth. All elements should be tightly packed, with the athletes’ motions fluidly blending together to convey a sense of speed and momentum, resulting in a cohesive, impactful banner design perfect for a mobile landscape layout.[ImageFX](seed 96358)`,
        `Create a high-energy, dynamic design that features four athletes and an F1 car — soccer, basketball, tennis, and racing —arranged closely together, leaving minimal negative space. The composition utilizes a dramatic worm's-eye view to make the athletes and the F1 car appear larger, emphasizing their power and motion. In the foreground, the basketball player, dressed in an orange jersey, is captured mid- dunk, his body filling the frame with the ball about to slam through the net. Just to the right, the soccer player, in a dark grey jersey with orange accents, locks his foot in motion, almost touching the basketball player's arm as the ball heads toward the goal. His body is angled, eyes focused on the ball with intensity. Behind the soccer player, the F1 car is blurred by speed, its front tires nearly overlapping the basketball player's leg, enhancing the sense of rush and movement. On the left side of the frame, the female tennis player in an orange jersey is captured mid-swing, performing a backhand shot, with her racket slicing through the air just before striking the tennis ball. The golden hour lighting bathes the scene, casting warm glows and long shadows that highlight each athlete's physicality and action, while also accentuating the sleek design of the F1 car. The subtle stadium background adds atmosphere, and a bold, diagonal orange vector runs behind the athletes and the car, tying the elements together and enhancing the dynamic, modern feel. Thin, semi-transparent vector lines, parallel to the main vector, add depth and additional layers, making the entire composition feel cohesive and energetic. The athletes ' motion s blend fluidly with the F1 car ’s speed, creating a sense of intensity, momentum, and speed. This results in a power ful, cohesive, and fast-paced banner design, perfect for a mobile landscape layout.[ImageFX](seed 280251)`,
        `Create a high-energy, dynamic design featuring four athletes and an F1 car—soccer, basketball, tennis, and racing—arranged closely together with minimal negative space. The composition should use a dramatic worm’s-eye view to make the athletes and the F1 car appear larger and more powerful. In the foreground, the soccer player, dressed in an orange jersey with white accents, is the central figure, captured mid-motion as he runs toward a soccer ball positioned slightly above eye level. He’s about to leap and strike the ball with his head, body leaning forward, arms outstretched, and eyes locked on the ball, shouting instructions to teammates. His intensity commands the scene. Just behind him, the F1 car speeds toward the viewer, its sleek design slightly angled to emphasize the rush of movement, adding a sense of speed and power. To the left, the basketball player, in a dark grey jersey with orange accents, dribbles the ball low to the ground, facing the camera, with the golden hour lighting reflecting off the ball, adding depth. To the right, the female tennis player, in a white jersey, is mid-swing, executing a powerful backhand shot, her racket slicing through the air with grace and force. The warm golden hour lighting bathes the athletes, casting long shadows and highlighting their motion, while also giving the F1 car’s design a sleek shine.`,
    ],
    deposit: [
        `The large gold coin with an embossed "$" sign glows softly, positioned at the center of the composition, slightly angled about 1/2 toward the camera to create a dynamic sense of depth. A white spotlight is cast directly onto the main coin, highlighting its embossed "$" symbol and making it the focal point of the composition. The gold of the "$" is significantly shinier and more radiant than the other coins, catching the light brilliantly. The raised design stands out due to subtle texturing and lighting that enhances its edges, making them gleam and glow with striking effect. This soft, luminous glow emphasizes the "$" symbol and draws the viewer’s attention. Beneath the main coin rests a stack of two smaller, less shiny gold coins, forming a vertical line of shimmering coins. The stack sits on a luxurious casino table with a dark velvet surface, surrounded by a soft, glowing orange cove light around its edges, creating a warm, inviting atmosphere and accentuating the table’s texture. Flanking the central coin stack are three small gift boxes symmetrically arranged on either side. The gift boxes are dark-colored with subtle textures enhanced by soft lighting, each adorned with a shiny silver ribbon that reflects light, providing a sophisticated contrast to the darker tones. The cove lighting casts a backlight onto the gift boxes, subtly illuminating their edges and creating a glowing aura around them, emphasizing their shape and finish. The blurred background transitions into the soft lines of an elegant hallway, where warm ambient light pours through, casting subtle golden highlights. The hallway’s muted tones and faint gold accents add depth and refinement, tying the composition together with a luxurious and celebratory atmosphere. The dark gradient of the background further enhances the glowing gold elements, making them pop. The rich velvet texture of the table, elegant hallway backdrop, and soft orange lighting create a sense of luxury and opulence. The close framing ensures all elements feel interwoven, forming a cohesive and harmonious visual experience. This composition is perfectly suited for a horizontal mobile banner, highlighting the lavish bonus theme with a refined, celebratory tone. [ImageFX] (478515)`,
        `This polished concept emphasizes clean, dynamic design with photorealistic elements. At the center, a sleek, large flat-screen smartphone with slim bezels and a glowing angled display showcases the 188bet website, symbolizing digital interaction. Behind the phone and an oversized ATM card stands a joyful Asian man in his late 20s, wearing a dark grey polo with orange accents and dark jeans. He holds an orange gift box with a shiny silver ribbon, adding a celebratory tone. To the right of the phone, the giant ATM card features a gradient from light grey to dark grey with realistic texture, contrasting with the orange accents. A sleek card wallet is partially visible near the man, hinting at integration between traditional and digital finance. The background transitions from light grey to soft light orange, creating a warm, inviting atmosphere. A thick, straight diagonal orange vector line runs cleanly behind the phone and card, tying the layout together. The gift box, central to the narrative, features a premium embossed texture, symbolizing rewards and success. The color palette includes #FF9200 (orange for the gift box, accents, and vector lines), #C3C3C3 (light grey for the background and ATM card), #262626 (dark grey for the man's shirt and card), and #FFFFFF (white for highlights). Soft natural lighting highlights textures and surfaces, while subtle shadows and reflections enhance depth, making the scene polished and engaging. [ImageFX] (seed 549301)`,
        `The camera is positioned directly in front of a massive high-tech vault door, now fully open to reveal its intricate metallic details and glowing edges. The round top opening of the vault funnels soft light into the scene, emphasizing its futuristic design. At the center, behind the shiny 3D "DEPOSIT BONUS" text, gold coins spill forward in a dynamic cascade that leads the viewer’s eye toward the focal point. The coins gradually fade into the dim, shadowed back end of the vault, which remains subtly lit to maintain visual depth. Dim white spotlights shine directly above the text, creating a soft halo effect that enhances the dimensionality of the glowing lettering without overpowering it. Gentle shadows add depth to the dark interior while keeping the glowing text as the primary focus. The gold coins flow in a controlled manner, interacting naturally with surrounding elements. On the left, a half-buried soccer ball with realistic stitching subtly gleams, its texture contrasting with the surrounding metallic coins. On the right, a polished roulette wheel is partially submerged, its vibrant orange, red, and black segments adding bold color. Two translucent red dice sit centrally among the coins, their glossy surfaces catching ambient light and contributing vibrant highlights. At the heart of the composition, resting atop the coins, is an elegant gift box wrapped in matte dark grey with a faint diamond texture, adorned with a radiant gold ribbon that gleams under the spotlight. The background edges feature a faintly blurred vault room with secure storage compartments and glowing lines, ensuring focus remains on the foreground. The vault’s round opening frames the scene and reinforces the focus on the glowing "DEPOSIT BONUS" text. [ImageFX] (565041)`,
    ],
    welcomeBonus: [
        `A photorealistic scene captured from an exaggerated camera angle for a dynamic, immersive perspective. A golden envelope in a rich, deep hue leans slightly against a stack of golden casino chips, emphasizing luxury and balance. Its open flap reveals more of the upright dark card inside, featuring large, embossed "WELCOME BONUS" text in shimmering gold. The card’s luxurious surface reflects soft, focused lighting, resting atop plush dark grey velvet fabric. Inside the envelope, a partially visible elegant casino chip adds exclusivity, while a polished pair of reflective dice sits beside it. A sparkling diamond rests delicately near the dice, enhancing the opulent tone. The card’s edges gleam subtly, highlighting its fine craftsmanship. In the softly blurred background, hints of champagne glasses and gold décor reinforce the luxurious, celebratory atmosphere. [ImageFX] (456893)`,
        `A dramatic, exaggerated camera angle creates an immersive perspective centered on an elegant black gift box adorned with a satin white ribbon. The box rests on a dark grey marble table, its surface detailed with intricate silver patterns that catch the light with sophisticated flair. The lid is slightly ajar, revealing a dark-colored card with a bold golden border and embossed "WELCOME BONUS" text in shimmering gold. The card's rich texture and centered placement make it the focal point, framed by neatly folded matte silver tissue paper that adds soft translucency and modern elegance. The angled composition leads the eye along the table’s subtle reflections toward the card. Three polished golden casino chips add depth—one leans naturally against the box while two lie nearby. A miniature golden 3D soccer ball and a golden 3D spade suit are carefully placed, reinforcing the luxurious gaming theme. [ImageFX] (seed 487536)`,
        ``,
    ]
}

const imageData = [
    //All categories should be in uppercase letters
    //Basketball
    { src: 'https://188betpromo.com/sandbox/banners/BASKETBALL-1.jpg', categories: ['BASKETBALL', 'SPORTS', 'FACE-OFF'], prompt: promptKeys.basketBall[0] },
    { src: 'https://188betpromo.com/sandbox/banners/BASKETBALL-2.jpg', categories: ['BASKETBALL', 'SPORTS', 'FACE-OFF'], prompt: promptKeys.basketBall[1] },
    { src: 'https://188betpromo.com/sandbox/banners/BASKETBALL-3.jpg', categories: ['BASKETBALL', 'SPORTS', 'TROPHY'], prompt: promptKeys.basketBall[2] },
    { src: 'https://188betpromo.com/sandbox/banners/BASKETBALL-4.jpg', categories: ['BASKETBALL', 'SPORTS',], prompt: promptKeys.basketBall[3] },
    { src: 'https://188betpromo.com/sandbox/banners/BASKETBALL-5.jpg', categories: ['BASKETBALL', 'SPORTS',], prompt: promptKeys.basketBall[4] },
    //CSGO
    { src: 'https://188betpromo.com/sandbox/banners/CSGO-1.jpg', categories: ['COUNTER-STRIKE', 'ESPORTS', 'ACTION'], prompt: promptKeys.csgo[0] },
    { src: 'https://188betpromo.com/sandbox/banners/CSGO-2.jpg', categories: ['COUNTER-STRIKE', 'ESPORTS', 'FACE-OFF'], prompt: promptKeys.csgo[1] },
    { src: 'https://188betpromo.com/sandbox/banners/CSGO-3.jpg', categories: ['COUNTER-STRIKE', 'ESPORTS'], prompt: promptKeys.csgo[2] },
    { src: 'https://188betpromo.com/sandbox/banners/CSGO-4.jpg', categories: ['COUNTER-STRIKE', 'ESPORTS', 'TROPHY'], prompt: promptKeys.csgo[3] },
    { src: 'https://188betpromo.com/sandbox/banners/CSGO-5.jpg', categories: ['COUNTER-STRIKE', 'ESPORTS', 'TROPHY'], prompt: promptKeys.csgo[4] },
    //LOL
    { src: 'https://188betpromo.com/sandbox/banners/LOL-1.jpg', categories: ['LEAGUE OF LEGENDS', 'ESPORTS', 'CHAMPIONSHIP'], prompt: promptKeys.lol[0] },
    { src: 'https://188betpromo.com/sandbox/banners/LOL-2.jpg', categories: ['LEAGUE OF LEGENDS', 'ESPORTS',], prompt: promptKeys.lol[1] },
    { src: 'https://188betpromo.com/sandbox/banners/LOL-3.jpg', categories: ['LEAGUE OF LEGENDS', 'ESPORTS', 'TROPHY'], prompt: promptKeys.lol[2] },
    { src: 'https://188betpromo.com/sandbox/banners/LOL-4.jpg', categories: ['LEAGUE OF LEGENDS', 'ESPORTS', 'ACTION'], prompt: promptKeys.lol[3] },
    //Parlay
    { src: 'https://188betpromo.com/sandbox/banners/PARLAY-1.png', categories: ['PARLAY'], prompt: promptKeys.parlay[0] },
    { src: 'https://188betpromo.com/sandbox/banners/PARLAY-2.jpg', categories: ['PARLAY'], prompt: promptKeys.parlay[1] },
    { src: 'https://188betpromo.com/sandbox/banners/PARLAY-3.jpg', categories: ['PARLAY'], prompt: promptKeys.parlay[2] },
    { src: 'https://188betpromo.com/sandbox/banners/PARLAY-4.jpg', categories: ['PARLAY'], prompt: promptKeys.parlay[3] },
    { src: 'https://188betpromo.com/sandbox/banners/PARLAY-5.jpg', categories: ['PARLAY'], prompt: promptKeys.parlay[4] },
    //Dota 2
    { src: 'https://188betpromo.com/sandbox/banners/DOTA-1.jpg', categories: ['DOTA 2', 'ESPORTS', 'TROPHY'], prompt: promptKeys.dota2[0] },
    { src: 'https://188betpromo.com/sandbox/banners/DOTA-2.jpg', categories: ['DOTA 2', 'ESPORTS',], prompt: promptKeys.dota2[1] },
    { src: 'https://188betpromo.com/sandbox/banners/DOTA-3.jpg', categories: ['DOTA 2', 'ESPORTS',], prompt: promptKeys.dota2[2] },
    { src: 'https://188betpromo.com/sandbox/banners/DOTA-4.jpg', categories: ['DOTA 2', 'ESPORTS', 'FACE-OFF', 'TROPHY'], prompt: promptKeys.dota2[3] },
    { src: 'https://188betpromo.com/sandbox/banners/DOTA-5.jpg', categories: ['DOTA 2', 'ESPORTS',], prompt: promptKeys.dota2[4] },
    //Football
    { src: 'https://188betpromo.com/sandbox/banners/FOOTBALL-1.jpg', categories: ['FOOTBALL', 'SPORTS', 'TROPHY'], prompt: promptKeys.football[0] },
    { src: 'https://188betpromo.com/sandbox/banners/FOOTBALL-2.jpg', categories: ['FOOTBALL', 'CHAMPIONSHIP', 'SPORTS', 'TROPHY'], prompt: promptKeys.football[1] },
    { src: 'https://188betpromo.com/sandbox/banners/FOOTBALL-3.jpg', categories: ['FOOTBALL', 'SPORTS', 'TROPHY'], prompt: promptKeys.football[2] },
    { src: 'https://188betpromo.com/sandbox/banners/FOOTBALL-4.jpg', categories: ['FOOTBALL', 'SPORTS'], prompt: promptKeys.football[3] },
    { src: 'https://188betpromo.com/sandbox/banners/FOOTBALL-5.jpg', categories: ['FOOTBALL', 'SPORTS'], prompt: promptKeys.football[4] },
    //FTD
    { src: 'https://188betpromo.com/sandbox/banners/FTD-1.jpg', categories: ['FIRST TIME DEPOSIT'], prompt: promptKeys.ftd[0] },
    { src: 'https://188betpromo.com/sandbox/banners/FTD-2.jpg', categories: ['FIRST TIME DEPOSIT'], prompt: promptKeys.ftd[1] },
    { src: 'https://188betpromo.com/sandbox/banners/FTD-3.jpg', categories: ['FIRST TIME DEPOSIT'], prompt: promptKeys.ftd[2] },
    { src: 'https://188betpromo.com/sandbox/banners/FTD-4.jpg', categories: ['FIRST TIME DEPOSIT'], prompt: promptKeys.ftd[3] },
    { src: 'https://188betpromo.com/sandbox/banners/FTD-5.jpg', categories: ['FIRST TIME DEPOSIT'], prompt: promptKeys.ftd[4] },
    //Free Bet
    { src: 'https://188betpromo.com/sandbox/banners/FREEBET-1.jpg', categories: ['FREE BET'], prompt: promptKeys.freebet[0] },
    { src: 'https://188betpromo.com/sandbox/banners/FREEBET-2.jpg', categories: ['FREE BET'], prompt: promptKeys.freebet[1] },
    { src: 'https://188betpromo.com/sandbox/banners/FREEBET-3.jpg', categories: ['FREE BET'], prompt: promptKeys.freebet[2] },
    { src: 'https://188betpromo.com/sandbox/banners/FREEBET-4.jpg', categories: ['FREE BET'], prompt: promptKeys.freebet[3] },
    { src: 'https://188betpromo.com/sandbox/banners/FREEBET-5.jpg', categories: ['FREE BET'], prompt: promptKeys.freebet[4] },
    { src: 'https://188betpromo.com/sandbox/banners/FREEBET-6.jpg', categories: ['FREE BET'], prompt: promptKeys.freebet[5] },
    //Rebate
    { src: 'https://188betpromo.com/sandbox/banners/REBATE-2.jpg', categories: ['REBATE'], prompt: promptKeys.rebate[0] },
    { src: 'https://188betpromo.com/sandbox/banners/REBATE-1.jpg', categories: ['REBATE'], prompt: promptKeys.rebate[1] },
    { src: 'https://188betpromo.com/sandbox/banners/REBATE-3.jpg', categories: ['REBATE'], prompt: promptKeys.rebate[2] },
    { src: 'https://188betpromo.com/sandbox/banners/REBATE-4.jpg', categories: ['REBATE'], prompt: promptKeys.rebate[3] },
    { src: 'https://188betpromo.com/sandbox/banners/REBATE-5.jpg', categories: ['REBATE'], prompt: promptKeys.rebate[4] },
    //Referral
    { src: 'https://188betpromo.com/sandbox/banners/REFERRAL-1.jpg', categories: ['REFERRAL'], prompt: promptKeys.referral[0] },
    { src: 'https://188betpromo.com/sandbox/banners/REFERRAL-2.jpg', categories: ['REFERRAL'], prompt: promptKeys.referral[1] },
    { src: 'https://188betpromo.com/sandbox/banners/REFERRAL-3.jpg', categories: ['REFERRAL'], prompt: promptKeys.referral[2] },
    //Match Banner
    { src: 'https://188betpromo.com/sandbox/banners/MATCHBANNER-1.jpg', categories: ['MATCH BANNER', 'TROPHY'], prompt: promptKeys.matchBanner[0] },
    { src: 'https://188betpromo.com/sandbox/banners/MATCHBANNER-2.jpg', categories: ['MATCH BANNER', 'TROPHY'], prompt: promptKeys.matchBanner[1] },
    { src: 'https://188betpromo.com/sandbox/banners/MATCHBANNER-3.jpg', categories: ['MATCH BANNER', 'TROPHY'], prompt: promptKeys.matchBanner[2] },
    //Multiple Sports
    { src: 'https://188betpromo.com/sandbox/banners/MULTISPORT-1.jpg', categories: ['MULTIPLE SPORTS', 'TROPHY'], prompt: promptKeys.multipleSports[0] },
    { src: 'https://188betpromo.com/sandbox/banners/MULTISPORT-2.jpg', categories: ['MULTIPLE SPORTS',], prompt: promptKeys.multipleSports[1] },
    { src: 'https://188betpromo.com/sandbox/banners/MULTISPORT-3.jpg', categories: ['MULTIPLE SPORTS',], prompt: promptKeys.multipleSports[2] },
    { src: 'https://188betpromo.com/sandbox/banners/MULTISPORT-4.jpg', categories: ['MULTIPLE SPORTS',], prompt: promptKeys.multipleSports[3] },
    { src: 'https://188betpromo.com/sandbox/banners/MULTISPORT-5.jpg', categories: ['MULTIPLE SPORTS',], prompt: promptKeys.multipleSports[4] },
    //DEPOSIT
    { src: 'https://188betpromo.com/sandbox/banners/DEPOSIT-1.jpg', categories: ['DEPOSIT',], prompt: promptKeys.deposit[0] },
    { src: 'https://188betpromo.com/sandbox/banners/DEPOSIT-2.jpg', categories: ['DEPOSIT',], prompt: promptKeys.deposit[1] },
    { src: 'https://188betpromo.com/sandbox/banners/DEPOSIT-3.jpg', categories: ['DEPOSIT',], prompt: promptKeys.deposit[2] },
    //WELCOME BONUS
    { src: 'https://188betpromo.com/sandbox/banners/WELCOMEBONUS-1.jpg', categories: ['WELCOME BONUS',], prompt: promptKeys.welcomeBonus[0] },
    { src: 'https://188betpromo.com/sandbox/banners/WELCOMEBONUS-2.jpg', categories: ['WELCOME BONUS',], prompt: promptKeys.welcomeBonus[1] },
    { src: 'https://188betpromo.com/sandbox/banners/WELCOMEBONUS-3.jpg', categories: ['WELCOME BONUS',], prompt: promptKeys.welcomeBonus[2] },
];


